#!/usr/bin/env python3
"""Generate TypeScript BMS client constants from docs/register_catalog.json.

This companion generator exists so the WeChat Mini Program can consume the same
protocol source of truth as Swift/Kotlin/Python/C++ clients. It deliberately
imports the existing catalog parser instead of maintaining a second register map.
"""
from __future__ import annotations

from bms_client_asset_tool import (
    GENERATED_DIR,
    REGISTER_CATALOG_PATH,
    ROOT,
    _collect_register_constants,
    _load_json,
)

MINIPROGRAM_OUTPUT = (
    ROOT
    / "vendor"
    / "ble_sample"
    / "BMSAssistantMiniProgram"
    / "generated"
    / "BMSGeneratedRegisterCatalog.ts"
)
DOCS_OUTPUT = GENERATED_DIR / "BMSGeneratedRegisterCatalog.ts"


def _status_bits(catalog: dict) -> list[dict]:
    for block in catalog.get("register_blocks", []):
        if block.get("id") == "system_status":
            return list(block.get("bit_flags", []))
    return []


def render_typescript(catalog: dict) -> str:
    gatt = catalog["ble_transport"]["gatt"]
    constraints = catalog["ble_transport"]["link_constraints"]
    constants = _collect_register_constants(catalog)
    bits = _status_bits(catalog)

    lines = [
        "// Auto-generated by script/bms_client_typescript_asset.py",
        "// Source: docs/register_catalog.json",
        "// Do not edit manually.",
        "",
        "export const BMSGeneratedUUIDs = {",
        f"  SERVICE_UUID: '{gatt['service_uuid']}',",
        f"  REQUEST_CHARACTERISTIC_UUID: '{gatt['request_characteristic_uuid']}',",
        f"  RESPONSE_CHARACTERISTIC_UUID: '{gatt['response_characteristic_uuid']}',",
        "} as const;",
        "",
        "export const BMSGeneratedBLEConstraints = {",
        f"  DEFAULT_ATT_MTU: {int(constraints['default_att_mtu'])},",
        f"  SAFE_SINGLE_REQUEST_PAYLOAD_BYTES: {int(constraints['safe_single_request_payload_bytes'])},",
        f"  RESPONSE_NOTIFY_FRAGMENT_BYTES: {int(constraints['response_notify_fragment_bytes'])},",
        "} as const;",
        "",
        "export const BMSGeneratedRegisterCatalog = {",
    ]
    for name, _kind, value in constants:
        if value > 9:
            lines.append(f"  {name}: 0x{value:04X},")
        else:
            lines.append(f"  {name}: {value},")
    lines.extend(["} as const;", "", "export const BMSSystemStatusBits = ["])
    for bit in bits:
        key = str(bit["key"]).replace("'", "\\'")
        title = str(bit.get("title_zh", key)).replace("'", "\\'")
        lines.append(f"  {{ bit: {int(bit['bit'])}, key: '{key}', title: '{title}' }},")
    lines.extend(["] as const;", ""])
    return "\n".join(lines)


def main() -> int:
    catalog = _load_json(REGISTER_CATALOG_PATH)
    content = render_typescript(catalog)
    for path in (DOCS_OUTPUT, MINIPROGRAM_OUTPUT):
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        print(f"[WRITE] {path.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
