#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import re
import sys
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
DOCS_DIR = ROOT / "docs"
GENERATED_DIR = DOCS_DIR / "generated"
REGISTER_CATALOG_PATH = DOCS_DIR / "register_catalog.json"
PROTOCOL_VECTORS_PATH = DOCS_DIR / "protocol_test_vectors.json"
QT_PROJECT_ROOT = ROOT / "vendor" / "ble_sample" / "BMSAssistantQt"


def _load_json(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def _parse_hex_int(value: Any) -> int:
    if isinstance(value, int):
        return value
    text = str(value).strip()
    if text.lower().startswith("0x"):
        return int(text, 16)
    return int(text, 10)


def _parse_hex_bytes(text: str) -> bytes:
    normalized = text.replace(" ", "").replace("\n", "").replace("\t", "")
    return bytes.fromhex(normalized)


def _upper_snake(text: str) -> str:
    cleaned = re.sub(r"[^0-9A-Za-z]+", "_", text)
    cleaned = re.sub(r"_+", "_", cleaned).strip("_")
    if not cleaned:
        return "UNNAMED"
    if cleaned[0].isdigit():
        cleaned = f"N_{cleaned}"
    return cleaned.upper()


def _swift_string(text: str) -> str:
    return text.replace("\\", "\\\\").replace("\"", "\\\"")


def _header_lines() -> list[str]:
    return [
        "// Auto-generated by script/bms_client_asset_tool.py",
        "// Source: docs/register_catalog.json",
        "// Do not edit manually.",
        "",
    ]


def _collect_register_constants(catalog: dict[str, Any]) -> list[tuple[str, str, int]]:
    constants: list[tuple[str, str, int]] = []
    for block in catalog["register_blocks"]:
        block_prefix = _upper_snake(block["id"])
        if "start_address" in block:
            constants.append((f"{block_prefix}_START", "uint16", _parse_hex_int(block["start_address"])))
        if "word_count" in block:
            constants.append((f"{block_prefix}_WORD_COUNT", "uint16", int(block["word_count"])))
        if "word_count_read" in block:
            constants.append((f"{block_prefix}_READ_WORD_COUNT", "uint16", int(block["word_count_read"])))
        if "magic_word" in block:
            constants.append((f"{block_prefix}_MAGIC", "uint16", _parse_hex_int(block["magic_word"])))

        for field in block.get("fields", []):
            field_prefix = f"{block_prefix}_{_upper_snake(field['id'])}"
            if "index" in field:
                constants.append((f"{field_prefix}_INDEX", "int", int(field["index"])))
            if "start_index" in field:
                constants.append((f"{field_prefix}_START_INDEX", "int", int(field["start_index"])))
            if "word_count" in field:
                constants.append((f"{field_prefix}_WORD_COUNT", "int", int(field["word_count"])))
            if "address" in field:
                constants.append((f"{field_prefix}_ADDRESS", "uint16", _parse_hex_int(field["address"])))
            if "start_address" in field:
                constants.append((f"{field_prefix}_START_ADDRESS", "uint16", _parse_hex_int(field["start_address"])))
            if "end_address" in field:
                constants.append((f"{field_prefix}_END_ADDRESS", "uint16", _parse_hex_int(field["end_address"])))

        for bit in block.get("bit_flags", []):
            constants.append((f"{block_prefix}_BIT_{_upper_snake(bit['key'])}", "int", int(bit["bit"])))

    return constants


def _render_swift(catalog: dict[str, Any]) -> str:
    lines = _header_lines()
    lines.append("import Foundation")
    lines.append("")
    lines.append("enum BMSGeneratedUUIDs {")
    lines.append(f"    static let SERVICE_UUID = \"{_swift_string(catalog['ble_transport']['gatt']['service_uuid'])}\"")
    lines.append(
        f"    static let REQUEST_CHARACTERISTIC_UUID = \"{_swift_string(catalog['ble_transport']['gatt']['request_characteristic_uuid'])}\""
    )
    lines.append(
        f"    static let RESPONSE_CHARACTERISTIC_UUID = \"{_swift_string(catalog['ble_transport']['gatt']['response_characteristic_uuid'])}\""
    )
    lines.append("}")
    lines.append("")
    lines.append("enum BMSGeneratedBLEConstraints {")
    lines.append(
        f"    static let DEFAULT_ATT_MTU: UInt16 = 0x{catalog['ble_transport']['link_constraints']['default_att_mtu']:04X}"
    )
    lines.append(
        "    static let SAFE_SINGLE_REQUEST_PAYLOAD_BYTES: Int = "
        f"{int(catalog['ble_transport']['link_constraints']['safe_single_request_payload_bytes'])}"
    )
    lines.append(
        "    static let RESPONSE_NOTIFY_FRAGMENT_BYTES: Int = "
        f"{int(catalog['ble_transport']['link_constraints']['response_notify_fragment_bytes'])}"
    )
    lines.append("}")
    lines.append("")
    lines.append("enum BMSGeneratedRegisterCatalog {")
    for name, kind, value in _collect_register_constants(catalog):
        swift_type = "Int" if kind == "int" else "UInt16"
        if kind == "int":
            lines.append(f"    static let {name}: {swift_type} = {value}")
        else:
            lines.append(f"    static let {name}: {swift_type} = 0x{value:04X}")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def _render_python(catalog: dict[str, Any]) -> str:
    lines = [
        '"""Auto-generated by script/bms_client_asset_tool.py. Do not edit manually."""',
        "",
        "class BMSGeneratedUUIDs:",
        f"    SERVICE_UUID = {catalog['ble_transport']['gatt']['service_uuid']!r}",
        f"    REQUEST_CHARACTERISTIC_UUID = {catalog['ble_transport']['gatt']['request_characteristic_uuid']!r}",
        f"    RESPONSE_CHARACTERISTIC_UUID = {catalog['ble_transport']['gatt']['response_characteristic_uuid']!r}",
        "",
        "class BMSGeneratedBLEConstraints:",
        f"    DEFAULT_ATT_MTU = {int(catalog['ble_transport']['link_constraints']['default_att_mtu'])}",
        (
            "    SAFE_SINGLE_REQUEST_PAYLOAD_BYTES = "
            f"{int(catalog['ble_transport']['link_constraints']['safe_single_request_payload_bytes'])}"
        ),
        (
            "    RESPONSE_NOTIFY_FRAGMENT_BYTES = "
            f"{int(catalog['ble_transport']['link_constraints']['response_notify_fragment_bytes'])}"
        ),
        "",
        "class BMSGeneratedRegisterCatalog:",
    ]
    for name, _kind, value in _collect_register_constants(catalog):
        if isinstance(value, int) and value > 9:
            lines.append(f"    {name} = 0x{value:04X}")
        else:
            lines.append(f"    {name} = {value}")
    lines.append("")
    return "\n".join(lines)


def _render_kotlin(catalog: dict[str, Any]) -> str:
    lines = _header_lines()
    lines.append("object BMSGeneratedUUIDs {")
    lines.append(f"    const val SERVICE_UUID = \"{catalog['ble_transport']['gatt']['service_uuid']}\"")
    lines.append(
        f"    const val REQUEST_CHARACTERISTIC_UUID = \"{catalog['ble_transport']['gatt']['request_characteristic_uuid']}\""
    )
    lines.append(
        f"    const val RESPONSE_CHARACTERISTIC_UUID = \"{catalog['ble_transport']['gatt']['response_characteristic_uuid']}\""
    )
    lines.append("}")
    lines.append("")
    lines.append("object BMSGeneratedBLEConstraints {")
    lines.append(f"    const val DEFAULT_ATT_MTU = 0x{int(catalog['ble_transport']['link_constraints']['default_att_mtu']):04X}")
    lines.append(
        "    const val SAFE_SINGLE_REQUEST_PAYLOAD_BYTES = "
        f"{int(catalog['ble_transport']['link_constraints']['safe_single_request_payload_bytes'])}"
    )
    lines.append(
        "    const val RESPONSE_NOTIFY_FRAGMENT_BYTES = "
        f"{int(catalog['ble_transport']['link_constraints']['response_notify_fragment_bytes'])}"
    )
    lines.append("}")
    lines.append("")
    lines.append("object BMSGeneratedRegisterCatalog {")
    for name, kind, value in _collect_register_constants(catalog):
        kotlin_type = "Int" if kind == "int" else "Int"
        if kind == "int":
            lines.append(f"    const val {name}: {kotlin_type} = {value}")
        else:
            lines.append(f"    const val {name}: {kotlin_type} = 0x{value:04X}")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def _render_cpp(catalog: dict[str, Any]) -> str:
    lines = _header_lines()
    lines.extend(
        [
            "#pragma once",
            "#include <cstdint>",
            "",
            "namespace bms_generated {",
            "namespace uuids {",
            f'inline constexpr const char* SERVICE_UUID = "{catalog["ble_transport"]["gatt"]["service_uuid"]}";',
            (
                "inline constexpr const char* REQUEST_CHARACTERISTIC_UUID = "
                f'"{catalog["ble_transport"]["gatt"]["request_characteristic_uuid"]}";'
            ),
            (
                "inline constexpr const char* RESPONSE_CHARACTERISTIC_UUID = "
                f'"{catalog["ble_transport"]["gatt"]["response_characteristic_uuid"]}";'
            ),
            "}  // namespace uuids",
            "",
            "namespace ble_constraints {",
            (
                "inline constexpr std::uint16_t DEFAULT_ATT_MTU = "
                f"0x{int(catalog['ble_transport']['link_constraints']['default_att_mtu']):04X};"
            ),
            (
                "inline constexpr int SAFE_SINGLE_REQUEST_PAYLOAD_BYTES = "
                f"{int(catalog['ble_transport']['link_constraints']['safe_single_request_payload_bytes'])};"
            ),
            (
                "inline constexpr int RESPONSE_NOTIFY_FRAGMENT_BYTES = "
                f"{int(catalog['ble_transport']['link_constraints']['response_notify_fragment_bytes'])};"
            ),
            "}  // namespace ble_constraints",
            "",
            "namespace register_catalog {",
        ]
    )
    for name, kind, value in _collect_register_constants(catalog):
        cpp_type = "int" if kind == "int" else "std::uint16_t"
        if kind == "int":
            lines.append(f"inline constexpr {cpp_type} {name} = {value};")
        else:
            lines.append(f"inline constexpr {cpp_type} {name} = 0x{value:04X};")
    lines.extend(["}  // namespace register_catalog", "}  // namespace bms_generated", ""])
    return "\n".join(lines)


def _render_generated_readme() -> str:
    return "\n".join(
        [
            "# Generated BMS Client Assets",
            "",
            "这些文件由 `script/bms_client_asset_tool.py generate` 自动生成。",
            "",
            "当前输出包括：",
            "",
            "- `BMSGeneratedRegisterCatalog.swift`",
            "- `bms_generated_register_catalog.py`",
            "- `BmsGeneratedRegisterCatalog.kt`",
            "- `bms_generated_register_catalog.hpp`",
            "",
            "请不要手工修改这些生成文件；如需更新，请修改：",
            "",
            "- `docs/register_catalog.json`",
            "- `script/bms_client_asset_tool.py`",
            "",
        ]
    )


@dataclass
class VerificationResult:
    passed: int = 0
    failed: int = 0

    def check(self, condition: bool, message: str) -> None:
        if condition:
            self.passed += 1
            print(f"[PASS] {message}")
        else:
            self.failed += 1
            print(f"[FAIL] {message}")


def generate_assets() -> None:
    catalog = _load_json(REGISTER_CATALOG_PATH)
    GENERATED_DIR.mkdir(parents=True, exist_ok=True)
    outputs = {
        GENERATED_DIR / "BMSGeneratedRegisterCatalog.swift": _render_swift(catalog),
        GENERATED_DIR / "bms_generated_register_catalog.py": _render_python(catalog),
        GENERATED_DIR / "BmsGeneratedRegisterCatalog.kt": _render_kotlin(catalog),
        GENERATED_DIR / "bms_generated_register_catalog.hpp": _render_cpp(catalog),
        GENERATED_DIR / "README.md": _render_generated_readme(),
    }
    for path, content in outputs.items():
        path.write_text(content, encoding="utf-8")
        print(f"[WRITE] {path.relative_to(ROOT)}")


def verify_assets() -> int:
    sys.path.insert(0, str(QT_PROJECT_ROOT))
    from bmsassistantqt.models import BatteryDataSource, BatteryStatusSnapshot
    from bmsassistantqt.protocol import (
        RegisterCatalog,
        ResponseAccumulator,
        echo,
        parse_response,
        read_holding,
        validate_crc,
        write_multiple,
        write_single,
    )

    vectors = _load_json(PROTOCOL_VECTORS_PATH)
    result = VerificationResult()

    for item in vectors["request_vectors"]:
        expected = _parse_hex_bytes(item["request_hex"])
        function_code = _parse_hex_int(item["function_code"])
        if function_code == 0x03:
            actual = read_holding(_parse_hex_int(item["start_address"]), int(item["quantity"]))
        elif function_code == 0x06:
            actual = write_single(_parse_hex_int(item["register"]), _parse_hex_int(item["value"]))
        elif function_code == 0x10:
            values = [_parse_hex_int(word) for word in item["values_words_hex"]]
            actual = write_multiple(_parse_hex_int(item["register"]), values)
        elif function_code == 0x7F:
            actual = echo(_parse_hex_bytes(item["payload_hex"]))
        else:
            raise ValueError(f"Unsupported function_code in vector: {item['id']}")

        result.check(actual == expected, f"request vector {item['id']} matches codec output")
        result.check(len(actual) == int(item["request_length_bytes"]), f"request vector {item['id']} length matches")
        if item.get("safe_for_single_ble_packet"):
            safe_limit = int(vectors["common_assumptions"]["safe_single_ble_request_bytes"])
            result.check(len(actual) <= safe_limit, f"request vector {item['id']} fits single BLE packet")

    for item in vectors["response_vectors"]:
        raw = _parse_hex_bytes(item["response_hex"])
        expected_error = item.get("expected_error")
        if expected_error:
            try:
                parse_response(raw)
                result.check(False, f"response vector {item['id']} should fail with {expected_error}")
            except Exception:
                if expected_error == "crc_mismatch":
                    result.check(not validate_crc(raw), f"response vector {item['id']} triggers CRC mismatch")
                else:
                    result.check(True, f"response vector {item['id']} fails as expected")
            continue

        parsed = parse_response(raw)
        expected = item["expected_parse"]
        result.check(parsed.kind == expected["kind"], f"response vector {item['id']} parse kind matches")
        if "words_hex" in expected:
            words = [_parse_hex_int(word) for word in expected["words_hex"]]
            result.check(list(parsed.words or []) == words, f"response vector {item['id']} words match")
        if "register" in expected:
            result.check(int(parsed.register or 0) == _parse_hex_int(expected["register"]), f"response vector {item['id']} register matches")
        if "value" in expected:
            result.check(int(parsed.value or 0) == _parse_hex_int(expected["value"]), f"response vector {item['id']} value matches")
        if "quantity" in expected:
            result.check(int(parsed.quantity or 0) == int(expected["quantity"]), f"response vector {item['id']} quantity matches")
        if "function" in expected:
            result.check(int(parsed.function or 0) == _parse_hex_int(expected["function"]), f"response vector {item['id']} function matches")
        if "code" in expected:
            result.check(int(parsed.code or 0) == _parse_hex_int(expected["code"]), f"response vector {item['id']} code matches")

    for item in vectors["accumulator_vectors"]:
        accumulator = ResponseAccumulator()
        fragments = [_parse_hex_bytes(text) for text in item["fragments_hex"]]
        first = accumulator.append(fragments[0])
        expected_first = item["expected"]["after_fragment_1"]
        result.check(first.state == expected_first["state"], f"accumulator vector {item['id']} first state matches")
        if "expected_length" in expected_first:
            result.check(first.expected_length == int(expected_first["expected_length"]), f"accumulator vector {item['id']} expected length matches")

        second = accumulator.append(fragments[1])
        expected_second = item["expected"]["after_fragment_2"]
        result.check(second.state == expected_second["state"], f"accumulator vector {item['id']} second state matches")
        if "frame_hex" in expected_second:
            result.check(second.frame == _parse_hex_bytes(expected_second["frame_hex"]), f"accumulator vector {item['id']} frame matches")

    source_map = {
        "legacy_registers": BatteryDataSource.LEGACY_REGISTERS,
        "realtime_window": BatteryDataSource.REALTIME_WINDOW,
    }

    for item in vectors["battery_snapshot_vectors"]:
        legacy_words = [0] * int(item["legacy_word_count"])
        for index_text, value_text in item["legacy_word_overrides_hex"].items():
            legacy_words[int(index_text)] = _parse_hex_int(value_text)
        status_words = [_parse_hex_int(word) for word in item["system_status_words_hex"]]
        realtime_words = [_parse_hex_int(word) for word in item["realtime_words_hex"]]
        snapshot = BatteryStatusSnapshot.decode(
            realtime_words=realtime_words,
            legacy_cell_words=legacy_words,
            system_status_words=status_words,
            register_catalog=RegisterCatalog,
            updated_at=datetime.now(),
        )
        expected = item["expected_decoded"]

        if "source" in expected:
            result.check(snapshot.source == source_map[expected["source"]], f"battery vector {item['id']} source matches")
        if "supports_realtime_window" in expected:
            result.check(snapshot.supports_realtime_window == bool(expected["supports_realtime_window"]), f"battery vector {item['id']} realtime support matches")

        comparable_fields = [
            "protocol_version",
            "pack_voltage_raw",
            "signed_current_raw",
            "soc_raw",
            "max_temp_raw",
            "min_temp_raw",
            "mos_temp_raw",
            "max_cell_voltage_raw",
            "min_cell_voltage_raw",
            "cell_delta_raw",
            "max_cell_position",
            "min_cell_position",
            "soh_raw",
            "capacity_now_raw",
            "capacity_full_raw",
            "capacity_factory_raw",
            "cycle_count_raw",
            "legacy_pack_voltage_raw_mv",
        ]
        for field_name in comparable_fields:
            if field_name in expected:
                result.check(getattr(snapshot, field_name) == expected[field_name], f"battery vector {item['id']} field {field_name} matches")

        if "active_status_flags" in expected:
            actual_flags = [flag.key for flag in snapshot.active_status_flags]
            result.check(actual_flags == expected["active_status_flags"], f"battery vector {item['id']} active flags match")

    print(f"[SUMMARY] passed={result.passed} failed={result.failed}")
    return 0 if result.failed == 0 else 1


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate and verify cross-platform BMS client assets.")
    subparsers = parser.add_subparsers(dest="command", required=True)
    subparsers.add_parser("generate", help="Generate language-specific register catalog assets.")
    subparsers.add_parser("verify", help="Verify protocol vectors and battery snapshot vectors against current Python implementation.")
    subparsers.add_parser("all", help="Run generate then verify.")
    args = parser.parse_args()

    if args.command == "generate":
        generate_assets()
        return 0
    if args.command == "verify":
        return verify_assets()
    if args.command == "all":
        generate_assets()
        return verify_assets()
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
