/* 文件功能：各持久域更新编号的公共语义；产品输入决定 OTA 后保留或更新哪些配置。
 * bms/core/bms_update_policy.h；实际编译归属见各产品 sources.txt。
 */
#pragma once

#include <stdint.h>
#include "bms_parameter_policy.h"

/* 更新编号是发布策略，不是存储格式版本。 */
typedef enum {
    BMS_UPDATE_SW,
    BMS_UPDATE_AFE,
    BMS_UPDATE_BUSINESS,
    BMS_UPDATE_SOC,
    BMS_UPDATE_CALIBRATION,
    BMS_UPDATE_IDENTITY,
    BMS_UPDATE_SOC_STATE,
    BMS_UPDATE_FACTORY_RUNTIME,
    BMS_UPDATE_EVENTS,
    BMS_UPDATE_GROUP_COUNT
} bms_update_group_t;

#define BMS_UPDATE_CONFIG_GROUP_COUNT BMS_UPDATE_SOC_STATE

#if BMS_UPDATE_SW_REVISION < 1 || BMS_UPDATE_SW_REVISION > 65535
#error "BMS_UPDATE_SW_REVISION must be in 1..65535"
#endif
#if BMS_UPDATE_AFE_REVISION < 1 || BMS_UPDATE_AFE_REVISION > 65535
#error "BMS_UPDATE_AFE_REVISION must be in 1..65535"
#endif
#if BMS_UPDATE_BUSINESS_REVISION < 1 || BMS_UPDATE_BUSINESS_REVISION > 65535
#error "BMS_UPDATE_BUSINESS_REVISION must be in 1..65535"
#endif
#if BMS_UPDATE_SOC_REVISION < 1 || BMS_UPDATE_SOC_REVISION > 65535
#error "BMS_UPDATE_SOC_REVISION must be in 1..65535"
#endif
#if BMS_UPDATE_CALIBRATION_REVISION < 1 || BMS_UPDATE_CALIBRATION_REVISION > 65535
#error "BMS_UPDATE_CALIBRATION_REVISION must be in 1..65535"
#endif
#if BMS_UPDATE_IDENTITY_REVISION < 1 || BMS_UPDATE_IDENTITY_REVISION > 65535
#error "BMS_UPDATE_IDENTITY_REVISION must be in 1..65535"
#endif
#if BMS_UPDATE_SOC_STATE_REVISION < 1 || BMS_UPDATE_SOC_STATE_REVISION > 65535
#error "BMS_UPDATE_SOC_STATE_REVISION must be in 1..65535"
#endif
#if BMS_UPDATE_FACTORY_RUNTIME_REVISION < 1 || BMS_UPDATE_FACTORY_RUNTIME_REVISION > 65535
#error "BMS_UPDATE_FACTORY_RUNTIME_REVISION must be in 1..65535"
#endif
#if BMS_UPDATE_EVENTS_REVISION < 1 || BMS_UPDATE_EVENTS_REVISION > 65535
#error "BMS_UPDATE_EVENTS_REVISION must be in 1..65535"
#endif

static inline uint16_t bms_update_revision(bms_update_group_t group)
{
    static const uint16_t revisions[BMS_UPDATE_GROUP_COUNT] = {
        BMS_UPDATE_SW_REVISION,
        BMS_UPDATE_AFE_REVISION,
        BMS_UPDATE_BUSINESS_REVISION,
        BMS_UPDATE_SOC_REVISION,
        BMS_UPDATE_CALIBRATION_REVISION,
        BMS_UPDATE_IDENTITY_REVISION,
        BMS_UPDATE_SOC_STATE_REVISION,
        BMS_UPDATE_FACTORY_RUNTIME_REVISION,
        BMS_UPDATE_EVENTS_REVISION,
    };
    return (unsigned)group < BMS_UPDATE_GROUP_COUNT ? revisions[group] : 0u;
}
