#pragma once
#define BMS_PRODUCT_ID 8u
#define BMS_AFE_BACKEND 1
#define BMS_PRODUCT_CHEMISTRY D008_PRODUCT_CHEMISTRY
#define BMS_PRODUCT_SOC_PROFILE_ID D008_PRODUCT_SOC_PROFILE_ID
#include "d008_product_profile.h"
