/* 文件功能：D008 电池装配串数与化学体系配置。 */
#ifndef D008_PRODUCT_PROFILE_H_
#define D008_PRODUCT_PROFILE_H_

#include "bms_soc_defs.h"

/*
 * HS-D008 装配配置：仅拥有随装配变化的物理串数和化学体系/SOC 配置。
 * 固定板级/故障安全策略在 dvc1124_project_config.h；
 * 运行/持久保护分别由g_tParam.protect（软件）及 bms_afe_hw_profile_t（AFE 硬件）持有
 * 。
 */
/* 保持历史数字 ID，兼容构建脚本。 */
#define D008_PRODUCT_PROFILE_24S_LFP  1u
#define D008_PRODUCT_PROFILE_20S_NMC  2u
#define D008_PRODUCT_PROFILE_16S_LFP  3u

#ifndef D008_PRODUCT_PROFILE
#if BMS_PRODUCTION_BUILD
#error "D008 production requires an explicit D008_PRODUCT_PROFILE"
#endif
#define D008_PRODUCT_PROFILE D008_PRODUCT_PROFILE_16S_LFP
#endif

#if (D008_PRODUCT_PROFILE == D008_PRODUCT_PROFILE_16S_LFP)
#define D008_PRODUCT_CELL_COUNT       16u
#define D008_PRODUCT_CHEMISTRY        BMS_SOC_CHEMISTRY_LFP
#define D008_PRODUCT_SOC_PROFILE_ID   BMS_SOC_PROFILE_GENERIC_LFP
#define D008_PRODUCT_PROFILE_NAME     "D008-16S-LFP"
#elif (D008_PRODUCT_PROFILE == D008_PRODUCT_PROFILE_20S_NMC)
#define D008_PRODUCT_CELL_COUNT       20u
#define D008_PRODUCT_CHEMISTRY        BMS_SOC_CHEMISTRY_NMC
#define D008_PRODUCT_SOC_PROFILE_ID   BMS_SOC_PROFILE_GENERIC_NMC
#define D008_PRODUCT_PROFILE_NAME     "D008-20S-NMC"
#elif (D008_PRODUCT_PROFILE == D008_PRODUCT_PROFILE_24S_LFP)
#define D008_PRODUCT_CELL_COUNT       24u
#define D008_PRODUCT_CHEMISTRY        BMS_SOC_CHEMISTRY_LFP
#define D008_PRODUCT_SOC_PROFILE_ID   BMS_SOC_PROFILE_GENERIC_LFP
#define D008_PRODUCT_PROFILE_NAME     "D008-24S-LFP"
#else
#error "Unsupported D008_PRODUCT_PROFILE"
#endif

#if ((D008_PRODUCT_CELL_COUNT < 4u) || (D008_PRODUCT_CELL_COUNT > 24u))
#error "D008 product cell count is outside DVC1124-2 range"
#endif

#endif /* 条件编译结束： D008_PRODUCT_PROFILE_H_ */
