# =============================================================================
# bms_tools/build.mk
# -----------------------------------------------------------------------------
# Portable build driver for the TLSR8251 BMS firmware (vendor/ble_sample).
#
# This file is a THIN DRIVER: it defines the toolchain, flags and top-level
# targets. The per-source compile rules are generated into
#   $(BUILD_DIR)/sources.mk
# by bms_tools/bms.py before make is invoked. On Windows bms.py exposes the
# repository through a no-space junction because GNU Make 4.2.1 still splits
# prerequisite paths containing spaces even when the shell quoting is valid.
#
# Reproduces the EXACT toolchain, flags and link configuration that the
# Telink IoT Studio (Eclipse CDT) generated makefiles used:
#   * Toolchain : tc32-elf-gcc 4.5.1-tc32-1.3  (vendor GCC, DO NOT upgrade)
#   * Chip      : TLSR8251 / TLSR825x (B85 family, TC32 / DSP-enhanced RISC)
#   * Standard  : gnu99, -fshort-wchar, -fpack-struct, -fshort-enums
#
# DO NOT change compiler flags, linker config, ABI or libraries without an
# explicit baseline-comparison (bms.py baseline). Firmware behaviour must
# stay byte-equivalent to the Telink IDE build unless a change is intentionally
# requested and re-verified on hardware.
# =============================================================================

# ---- Paths (all passed in by bms.py; provide sensible defaults only). ------
REPO_ROOT    ?= $(CURDIR)
SDK_DIR      ?= $(REPO_ROOT)/tc_ble_single_sdk-V3.4.2.8_Patch_0001/tc_ble_single_sdk
PROJ_DIR     := $(SDK_DIR)/project/tlsr_tc32/B85
LINKER_FILE  := $(PROJ_DIR)/boot.link
PROJ_LIB_DIR := $(SDK_DIR)/proj_lib

BUILD_DIR    ?= $(REPO_ROOT)/build/bms
OBJ_DIR      := $(BUILD_DIR)/obj
GEN_DIR      := $(BUILD_DIR)/gen

# ---- Toolchain (vendor-supplied, fixed version) ---------------------------
CC      := tc32-elf-gcc
LD      := tc32-elf-ld
OBJCOPY := tc32-elf-objcopy
OBJDUMP := tc32-elf-objdump
SIZE    := tc32-elf-size

# ---- Artifacts ------------------------------------------------------------
ELF      := $(BUILD_DIR)/825x_ble_sample.elf
RAW_BIN  := $(BUILD_DIR)/825x_ble_sample.raw.bin
LST      := $(GEN_DIR)/825x_ble_sample.lst
MAP      := $(GEN_DIR)/825x_ble_sample.map

# ---- Include paths (exact set from Eclipse .cproject for B85/825x_sample) -
INCLUDES := \
	-I"$(PROJ_DIR)" \
	-I"$(SDK_DIR)" \
	-I"$(SDK_DIR)/vendor/common" \
	-I"$(SDK_DIR)/common" \
	-I"$(SDK_DIR)/drivers/B85"

# ---- Defines (exact set from Eclipse .cproject, B85 / 825x_ble_sample) ----
DEFINES := \
	-D__PROJECT_8258_BLE_SAMPLE__=1 \
	-DCHIP_TYPE=CHIP_TYPE_825x

# ---- Compile flags (EXACT match to Eclipse-generated subdir.mk) ----------
CFLAGS_BASE := \
	-ffunction-sections -fdata-sections \
	-Wall -O2 \
	-fpack-struct -fshort-enums -finline-small-functions \
	-std=gnu99 -fshort-wchar -fms-extensions

# Assembler defines (exact match to Eclipse-generated subdir.mk for boot/B85:
# the canonical command is `tc32-elf-gcc -DMCU_STARTUP_8258 -c`).
AFLAGS_BASE := -DMCU_STARTUP_8258

CFLAGS := $(CFLAGS_BASE) $(INCLUDES) $(DEFINES)
AFLAGS := $(AFLAGS_BASE)

# ---- Link flags (exact match to Eclipse makefile + objects.mk) -------------
LDFLAGS := --gc-sections -L"$(PROJ_LIB_DIR)" -T "$(LINKER_FILE)"
LIBS    := -llt_825x -llt_general_stack

# ---- Per-source rules: generated by bms.py into $(BUILD_DIR)/sources.mk --
# (defines OBJS, C_SRCS, ASM_SRCS and one rule per object)
-include $(BUILD_DIR)/sources.mk

# ---- Top-level targets ----------------------------------------------------
.PHONY: all clean size

all: $(ELF) $(RAW_BIN) $(LST) size

# Link. -Map produces the MAP file (Eclipse did NOT; we add it as a build-side
# asset for size/static analysis; it does NOT alter firmware bytes).
# Build dirs are pre-created by bms_tools/bms.py before make is invoked, so
# recipes do NOT use `mkdir -p` (Windows' built-in mkdir does not support -p).
$(ELF): $(OBJS)
	@echo 'Linking: $@'
	$(LD) $(LDFLAGS) -Map="$(MAP)" -o"$(ELF)" $(OBJS) $(LIBS)

# Raw binary (Eclipse post-build: tc32-elf-objcopy -v -O binary ...)
$(RAW_BIN): $(ELF)
	@echo 'Objcopy: $@'
	$(OBJCOPY) -v -O binary $(ELF) $(RAW_BIN)

# Extended listing (Eclipse: tc32-elf-objdump -x -l -S)
$(LST): $(ELF)
	$(OBJDUMP) -x -l -S $(ELF) > "$(LST)"

# MAP file is a side effect of link; declare it built alongside ELF.
$(MAP): $(ELF)

size: $(ELF)
	@echo 'Size:'
	$(SIZE) -t $(ELF)

clean:
	@echo 'Cleaning: $(BUILD_DIR)'
	@rm -rf "$(BUILD_DIR)"
