namespace TelinkOta.Core.Ota;

/// <summary>
/// 设备 OTA Result 码（0x00~0x0E）及用户可操作建议。依据 ota.h 与官方 App ResultCode。
/// </summary>
public sealed class OtaResult
{
    public byte Code { get; }
    public string Name { get; }
    public string Description { get; }
    public string UserAction { get; }

    private OtaResult(byte code, string name, string description, string userAction)
    {
        Code = code;
        Name = name;
        Description = description;
        UserAction = userAction;
    }

    public static OtaResult FromCode(byte code) => code switch
    {
        0x00 => new OtaResult(0x00, "OTA_SUCCESS", "success", "升级成功，等待设备重启并复核版本。"),
        0x01 => new OtaResult(0x01, "OTA_DATA_PACKET_SEQ_ERR",
            "OTA data packet sequence number error: repeated OTA PDU or lost some OTA PDU",
            "连接不稳定或发送窗口溢出导致丢包。请靠近设备后重连，从头重新升级。"),
        0x02 => new OtaResult(0x02, "OTA_PACKET_INVALID",
            "invalid OTA packet: invalid OTA command / addr_index out of range / not standard OTA PDU length",
            "命令或数据包格式异常。请检查 PDU 长度设置与协议版本，从头重新升级。"),
        0x03 => new OtaResult(0x03, "OTA_DATA_CRC_ERR", "packet PDU CRC err",
            "数据包 CRC16 校验失败。请检查 CRC16 实现、尾包 0xFF 补齐和 PDU 长度是否与 Start 声明一致。"),
        0x04 => new OtaResult(0x04, "OTA_WRITE_FLASH_ERR", "write OTA data to flash ERR",
            "设备 Flash 写入失败。请检查供电电压、Flash 解锁状态（Lock/Unlock）与目标分区。"),
        0x05 => new OtaResult(0x05, "OTA_DATA_INCOMPLETE", "lost last one or more OTA PDU",
            "尾部数据包缺失。发送窗口可能提前收尾，请从头重新升级。"),
        0x06 => new OtaResult(0x06, "OTA_FLOW_ERR", "peer device send OTA command or OTA data not in correct flow",
            "命令顺序错误（可能重复发送了 Start/End 或在错误时机发送数据）。请从头重新升级。"),
        0x07 => new OtaResult(0x07, "OTA_FW_CHECK_ERR", "firmware CRC check error",
            "固件 CRC32 校验失败：BIN 被修改、发送长度错误、尾部 CRC32 缺失/错误或选错固件。"),
        0x08 => new OtaResult(0x08, "OTA_VERSION_COMPARE_ERR",
            "the version number to be update is lower than the current version",
            "目标版本不高于设备当前版本。请使用更高版本固件，或在工程模式临时关闭版本比较。"),
        0x09 => new OtaResult(0x09, "OTA_PDU_LEN_ERR",
            "PDU length error: not 16*n, or not equal to the value it declare in CMD_OTA_START_EXT packet",
            "Start 声明 PDU 长度与实际数据包不一致或不是 16 的整数倍。请检查 PDU 长度设置。"),
        0x0A => new OtaResult(0x0A, "OTA_FIRMWARE_MARK_ERR", "firmware mark error: not generated by telink's BLE SDK",
            "Firmware Mark 错误：文件不是 Telink BLE SDK 工具链产物，或选错了产品固件。"),
        0x0B => new OtaResult(0x0B, "OTA_FW_SIZE_ERR",
            "firmware size error: no firmware_size; firmware size too small or too big",
            "固件尺寸非法：无 Size、文件过小或超过分区上限（本设备 124K）。"),
        0x0C => new OtaResult(0x0C, "OTA_DATA_PACKET_TIMEOUT",
            "time interval between two consequent packet exceed a value(user can adjust this value)",
            "相邻数据包间隔超过设备端 15 s。蓝牙链路拥塞或写入被阻塞，请重连后重试。"),
        0x0D => new OtaResult(0x0D, "OTA_TIMEOUT", "OTA flow total timeout",
            "OTA 总流程超过设备端 180 s。请提升吞吐（更大 PDU）或缩短固件，重试。"),
        0x0E => new OtaResult(0x0E, "OTA_FAIL_DUE_TO_CONNECTION_TERMINATE",
            "OTA fail due to current connection terminate",
            "OTA 期间连接终止。请重新连接后从头升级。"),
        _ => new OtaResult(code, $"UNKNOWN_0x{code:X2}", "unknown result code", "未知结果码，请提供完整日志给 FAE。"),
    };

    public override string ToString() => $"OTA result: {Code:X2} - {Name} - {Description}";
}
