<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\BmsTool.Android.Deployer\AndroidFirmwareSender.cs" Link="AndroidFirmwareSender.cs" />
    <Compile Include="..\BmsTool.Windows\ModbusRtu.cs" Link="ModbusRtu.cs" />
    <Compile Include="..\BmsTool.Windows\TelinkOtaProtocol.cs" Link="TelinkOtaProtocol.cs" />
    <Compile Include="..\Shared\TelinkOtaCore.cs" Link="TelinkOtaCore.cs" />
  </ItemGroup>
</Project>
